homepage: "https://github.com/haproxy/haproxy"
primary_contact: "adam@adalogics.com"
language: c++
auto_ccs:
  - "david@adalogics.com"
  - "timwolla@googlemail.com"
  - "willy@1wt.eu"
sanitizers:
  - address
