homepage: "https://matt.ucc.asn.au/dropbear/dropbear.html"
language: c++
primary_contact: "matt@ucc.asn.au"
sanitizers:
  - address
  - undefined
  - memory
fuzzing_engines:
  - libfuzzer
  - honggfuzz
