homepage: "https://github.com/openthread/openthread"
language: c++
primary_contact: "jonhui@google.com"
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
  - dataflow
sanitizers:
  - address
  - undefined
  - dataflow
