# action.yml
name: 'build-fuzzers'
description: "Builds an OSS-Fuzz project's fuzzers."
inputs:
  oss-fuzz-project-name:
    description: 'Name of the corresponding OSS-Fuzz project.'
    required: true
  dry-run:
    description: 'If set, run the action without actually reporting a failure.'
    default: false
  allowed-broken-targets-percentage:
    description: 'The percentage of broken targets allowed in bad_build_check.'
    required: false
  sanitizer:
    description: 'The sanitizer to build the fuzzers with.'
    default: 'address'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    OSS_FUZZ_PROJECT_NAME: ${{ inputs.oss-fuzz-project-name }}
    DRY_RUN: ${{ inputs.dry-run}}
    ALLOWED_BROKEN_TARGETS_PERCENTAGE: ${{ inputs.allowed-broken-targets-percentage}}
    SANITIZER: ${{ inputs.sanitizer }}
