homepage: "https://www.jbig2dec.com"
language: c++
primary_contact: sebastian.rasmussen@artifex.com
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
  - dataflow
sanitizers:
  - address
  - memory
  - dataflow
