homepage: "https://ghostscript.com"
language: c++
primary_contact: "skau@google.com"
auto_ccs:
  - "henry.stiles@artifex.com"
  - "skau@google.com"
  - "sebastian.rasmussen@artifex.com"
  - "julians.artifex@gmail.com"
  - "chris.liddell@artifex.com"
sanitizers:
  - address
  - memory
