homepage: "https://github.com/akheron/jansson"
language: c++
primary_contact: "git@cfware.com"
auto_ccs:
  - "cmeister2@gmail.com"
sanitizers:
  - address
  - memory
  - undefined
architectures:
  - x86_64
  - i386
